In [3]:
import numpy

In [5]:
a = numpy.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [7]:
type(a)

numpy.ndarray

In [12]:
mat = numpy.array([[1,2],[3,4]])
mat

array([[1, 2],
       [3, 4]])

In [16]:
print(mat[1][1])
print(mat[-1][-1])

4
4


In [18]:
mat[1,:] #coluna

array([3, 4])

In [19]:
mat[:,1] #coluna

array([2, 4])

In [21]:
mat.transpose()

array([[1, 3],
       [2, 4]])

In [23]:
m1 = numpy.array([[1,2],[3,4]])
m2 = numpy.array([[5,6],[7,8]])
m1+m2

array([[ 6,  8],
       [10, 12]])

In [25]:
m1-m2

array([[-4, -4],
       [-4, -4]])

In [26]:
m1*m2

array([[ 5, 12],
       [21, 32]])

In [27]:
m3 = numpy.array([1,2,3,4])
m3.sum()

10

In [29]:
m3.argmax()

3

In [30]:
m3.argmin()

0