In [1]:
import numpy as np

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [5]:
np.linspace(2.0, 3.0, 5)

array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])

In [6]:
np.linspace(2.0, 2.5, 5)

array([ 2.   ,  2.125,  2.25 ,  2.375,  2.5  ])